# Constants, sequences and random values - solutions

In [1]:
from __future__ import print_function
import mxnet as mx 
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2017, 12, 25)

In [3]:
author = "lambdaofgod. adapted from https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
mx.__version__

'0.12.1'

In [5]:
np.__version__

'1.12.1'

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Constant Value Tensors

Q1. Create a tensor of the shape [2, 3] with all elements set to zero.


In [6]:
out = mx.nd.zeros([2, 3])
assert np.allclose(out.asnumpy(), np.zeros([2, 3]))

Q2. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to zero.

In [7]:
_X = np.array([[1,2,3], [4,5,6]])
X = mx.nd.array(_X)
out = mx.nd.zeros_like(X)
print(out)
assert np.allclose(out.asnumpy(), np.zeros_like(_X))


[[ 0.  0.  0.]
 [ 0.  0.  0.]]
<NDArray 2x3 @cpu(0)>


Q3. Create a tensor of shape [2, 3] with all elements set to one.

In [8]:
out = mx.nd.ones([2, 3])
print(out)
assert np.allclose(out.asnumpy(), np.ones([2, 3]))


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>


Q4. Let X be a tensor of [[1,2,3], [4,5,6]]. <br />Create a tensor of the same shape and dtype as X with all elements set to one.

In [9]:
_X = np.array([[1,2,3], [4,5,6]])
X = mx.nd.array(_X)
out = mx.nd.ones_like(X)
print(out)
assert np.allclose(out.asnumpy(), np.ones_like(_X))
# tf.ones_like == np.ones_like


[[ 1.  1.  1.]
 [ 1.  1.  1.]]
<NDArray 2x3 @cpu(0)>


Q5. Create a tensor of the shape [3, 2], with all elements of 5.

In [10]:
out1 = mx.nd.full([3, 2], 5)
out2 = mx.nd.ones([3, 2]) * 5
assert np.allclose(out1.asnumpy(), out2.asnumpy())
print(out1.asnumpy())

[[ 5.  5.]
 [ 5.  5.]
 [ 5.  5.]]


Q6. Create a constant tensor of [[1, 3, 5], [4, 6, 8]], with dtype=float32

In [11]:
out = mx.nd.array([[1, 3, 5], [4, 6, 8]], dtype='float32')
print(out.asnumpy())
assert np.allclose(out.asnumpy(), np.array([[1, 3, 5], [4, 6, 8]], dtype=np.float32))

[[ 1.  3.  5.]
 [ 4.  6.  8.]]


Q7. Create a constant tensor of the shape [2, 3], with all elements set to 4.

In [12]:
out = mx.nd.full(val=4, shape=[2, 3])
print(out.asnumpy())
assert np.allclose(out.asnumpy(), np.full([2, 3], 4))

[[ 4.  4.  4.]
 [ 4.  4.  4.]]


## Sequences

Q8. Create a 1-D tensor of 50 evenly spaced elements between 5 and 10 inclusive.

This is equivalent to `np.linspace`. MXNet doesn't have such built-in functionality.

In [ ]:
out = mx.nd.???(5., 10., 50)
print(out.eval())
assert np.allclose(out.eval(), np.linspace(5., 10., 50))
# tf.linspace == np.linspace

Q9. Create a tensor which looks like [10, 12, 14, 16, ..., 100].

In [14]:
out = mx.nd.arange(10, 101, 2)
print(out.asnumpy())
assert np.allclose(out.asnumpy(), np.arange(10, 101, 2))

[  10.   12.   14.   16.   18.   20.   22.   24.   26.   28.   30.   32.
   34.   36.   38.   40.   42.   44.   46.   48.   50.   52.   54.   56.
   58.   60.   62.   64.   66.   68.   70.   72.   74.   76.   78.   80.
   82.   84.   86.   88.   90.   92.   94.   96.   98.  100.]


## Random Tensors

Q10. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=2.

In [15]:
X = mx.nd.random_normal(shape=[3, 2], loc=0, scale=2.)
print(X.asnumpy())
# mx.nd.random_normal is almost equivalent to np.random.normal
# But the order of the arguments is differnt.
# _X = np.random.normal(0, 2., [3, 2])


[[ 0.60061508  0.4621447 ]
 [ 2.09865785 -0.64867866]
 [-0.0195776   1.47372472]]


Q11. Create a random tensor of the shape [3, 2], with elements from a normal distribution of mean=0, standard deviation=1 such that any values don't exceed 2 standard deviations from the mean.

In [21]:
out = (
  mx.nd.clip(
    mx.nd.random_normal(shape=[3, 2]),
    a_max=2,
    a_min=-2)
)
print(out.asnumpy())

[[-0.43647185 -0.011113  ]
 [ 0.48286641  0.53347087]
 [-0.11204046  0.07230883]]


Q12. Create a random tensor of the shape [3, 2], with all elements from a uniform distribution that ranges from 0 to 2 (exclusive).

In [17]:
out = mx.nd.random_uniform(shape=[3, 2], low=0, high=2)
print(out.asnumpy())
# mx.nd.random_uniform is almost equivalent to np.random.uniform
# But the order of the arguments is differnt.
# _X = np.random.uniform(0, 2., [3, 2])

[[ 1.51974213  1.48588109]
 [ 1.52398443  1.6801821 ]
 [ 1.47731388  1.64930928]]


#### These last 2 exercises could be dropped - there are no such built-in functions in MXNet.

Q13. Let X be a tensor of [[1, 2], [3, 4], [5, 6]]. Shuffle X along its first dimension.

In [ ]:
_X = np.array([[1, 2], [3, 4], [5, 6]])
X = mx.nd.array(_X)
out = mx.nd.random_shuffle(X)
print(out.asnumpy())
# mx.nd.random_shuffle() is not a in-place function unlike np.random_shuffle().
# np.random.shuffle(_X)
# print(_X)

Q14. Let X be a random tensor of the shape [10, 10, 3], with elements from a unit normal distribution. Crop X with the shape of [5, 5, 3].

In [ ]:
X = tf.random_normal([10, 10, 3])
out = tf.random_crop(X, [5, 5, 3])
print(out.eval())