# Math Part 1

In [1]:
from __future__ import print_function
import mxnet
from mxnet import nd
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2017, 12, 27)

In [3]:
author = "lambdaofgod. based on https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
mxnet.__version__

'0.12.1'

In [5]:
np.__version__

'1.12.1'

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Arithmetic Operators

Q1. Add x and y element-wise.

In [6]:
_x = np.array([1, 2, 3])
_y = np.array([-1, -2, -3])
x = nd.array(_x)
y = nd.array(_y)
out1 = nd.add(x, y)
out2 = x + y 
print(out1)
assert np.array_equal(out1.asnumpy(), out2.asnumpy()) # nd.add is the same as the `+` operator.

_out = np.add(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.add == np.add


[ 0.  0.  0.]
<NDArray 3 @cpu(0)>


Q2. Subtract y from x element-wise.

In [7]:
_x = np.array([3, 4, 5])
_y = np.array([3])
x = nd.array(_x)
y = nd.array(_y)
out1 = nd.subtract(x, y)
out2 = x - y 
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy()) # nd.subtract is the same as the `-` operator.

_out = np.subtract(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.subtract == np.subtract
# `add`, `subtract`, `multiply`, `div`, and `mod` support broadcasting. 

[ 0.  1.  2.]


Q3. Multiply x by y element-wise.

In [8]:
_x = np.array([3, 4, 5])
_y = np.array([1, 0, -1])
x = nd.array(_x)
y = nd.array(_y)
out1 = nd.multiply(x, y)
out2 = x * y 
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy()) # nd.multiply is the same as the `*` operator.

_out = np.multiply(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.multiply == np.multiply

[ 3.  0. -5.]


Q4. Multiply x by 5 element-wise.

In [9]:
_x = np.array([1, 2, 3])
x = nd.array(_x)
out1 = nd.multiply(5, x)
out2 = x * 5
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = _x * 5
assert np.array_equal(out1.asnumpy(), _out)

[  5.  10.  15.]


Q5. Predict the result of this.

In [20]:
_x = np.array([10, 20, 30], np.int32)
_y = np.array([2, 3, 5], np.int32)
x = nd.array(_x, dtype='int32')
y = nd.array(_y, dtype='int32')
out1 = nd.divide(x, y)
out2 = x.astype('float64') / y.astype('float64')
print(np.array_equal(out1.asnumpy(), out2.asnumpy()))

print(out1.asnumpy(), out1.asnumpy().dtype) # nd.div() returns the same results as input tensors. 
print(out2.asnumpy(), out2.asnumpy().dtype)# nd.truediv() always returns floating point results.

_out1 = _x // _y
assert np.array_equal(out1.asnumpy(), _out1)

_out2 = _x / _y
assert np.array_equal(out2.asnumpy(), _out2)

False
[5 6 6] int32
[ 5.          6.66666667  6.        ] float64


Q6. Get the remainder of x / y element-wise.

In [22]:
_x = np.array([10, 20, 30], np.int32)
_y = np.array([2, 3, 7], np.int32)
x = nd.array(_x)
y = nd.array(_y)

out1 = nd.modulo(x, y)
out2 = x % y
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())# nd.mod() is the same as the `%` operator.

_out = _x % _y
assert np.array_equal(out1.asnumpy(), _out)


[ 0.  2.  2.]


Q7. Compute the pairwise cross product of x and y.

In [23]:
_x = np.array([1, 2, 3], np.int32)
_y = np.array([4, 5, 6], np.int32)
x = nd.array(_x)
y = nd.array(_y)

out1 = nd.cr(x, y)
print(out1.asnumpy())

_out = np.cross(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.cross == np.cross

AttributeError: module 'mxnet.ndarray' has no attribute 'cross'

## Basic Math Functions

Q8. Add x, y, and z element-wise.

In [26]:
_x = np.array([1, 2, 3], np.int32)
_y = np.array([4, 5, 6], np.int32)
_z = np.array([7, 8, 9], np.int32)
x = nd.array(_x)
y = nd.array(_y)
z = nd.array(_y)

out1 = nd.add_n(x, y, z)
out2 = x + y + z
print(out1.asnumpy())

assert np.array_equal(out1.asnumpy(), out2.asnumpy())

[  9.  12.  15.]


Q9. Compute the absolute value of X element-wise.

In [28]:
_X = np.array([[1, -1], [3, -3]])
X = nd.array(_X)

out = nd.abs(X)
print(out.asnumpy())

_out = np.abs(_X)
assert np.array_equal(out.asnumpy(), _out) # nd.abs == np.abs

[[ 1.  1.]
 [ 3.  3.]]


Q10. Compute numerical negative value of x, elemet-wise.


In [30]:
_x = np.array([1, -1])
x = nd.array(_x)

out1 = nd.negative(x)
out2 = -x
print(out.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = np.negative(_x)
assert np.array_equal(out1.asnumpy(), _out) # nd.negative == np.negative

[[ 1.  1.]
 [ 3.  3.]]


Q11. Compute an element-wise indication of the sign of x, element-wise.

In [31]:
_x = np.array([1, 3, 0, -1, -3])
x = nd.array(_x)

out = nd.sign(x)
print(out.asnumpy())

_out = np.sign(_x)
assert np.array_equal(out.asnumpy(), _out) # nd.sign == np.sign

[ 1.  1.  0. -1. -1.]


Q12. Compute the reciprocal of x, element-wise.

In [32]:
_x = np.array([1, 2, 2/10])
x = nd.array(_x)

out1 = nd.reciprocal(x)
out2 = 1/x
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = np.reciprocal(_x)
assert np.array_equal(out1.asnumpy(), _out) # nd.reciprocal == np.reciprocal

[ 1.   0.5  5. ]


Q13. Compute the square of x, element-wise.

In [33]:
_x = np.array([1, 2, -1])
x = nd.array(_x)

out1 = nd.square(x)
out2 = x * x
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = np.square(_x)
assert np.array_equal(out1.asnumpy(), _out) # nd.square == np.square

[ 1.  4.  1.]


Q14. Predict the results of this, paying attention to the difference among the family functions.

In [71]:
_x = np.array([2.1, 1.5, 2.5, 2.9, -2.1, -2.5, -2.9])
x = nd.array(_x)

out1 = nd.round(x)
out2 = nd.floor(x)
out3 = nd.ceil(x)
print(out1.asnumpy())
print(out2.asnumpy())
print(out3.asnumpy())

_out1 = np.round(_x)
_out2 = np.floor(_x)
_out3 = np.ceil(_x)
assert np.array_equal(out1.asnumpy(), _out1) # nd.round == np.around
assert np.array_equal(out2.asnumpy(), _out2) # nd.floor == np.floor
assert np.array_equal(out3.asnumpy(), _out3) # nd.ceil == np.ceil

[ 1.  1.  1.  1. -2. -2. -2.]
[ 2.  2.  2.  2. -1. -1. -1.]


Q15. Compute square root of x element-wise.

In [49]:
_x = np.array([1, 4, 9], dtype=np.float32)
x = nd.array(_x)

out = nd.sqrt(x)
print(out.asnumpy())

_out = np.sqrt(_x)
assert np.array_equal(out.asnumpy(), _out) # nd.sqrt ≈ np.sqrt
# Note that in TensorFlow, the input tensor must be
# a float, whereas in Numpy, an integer is okay.

[ 1.  2.  3.]


Q16. Compute the reciprocal of square root of x element-wise.

In [51]:
_x = np.array([1., 4., 9.])
x = nd.array(_x)

out1 = nd.rsqrt(x)
out2 = nd.reciprocal(nd.sqrt(x))
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

[ 1.          0.5         0.33333334]


Q17. Compute $x^y$, element-wise.

In [53]:
_x = np.array([[1, 2], [3, 4]])
_y = np.array([[1, 2], [1, 2]])
x = nd.array(_x)
y = nd.array(_y)

out = x ** y
print(out.asnumpy())

_out = np.power(_x, _y)
assert np.array_equal(out.asnumpy(), _out) # nd.pow == np.power

[[  1.   4.]
 [  3.  16.]]


Q17. Compute $e^x$, element-wise.

In [55]:
_x = np.array([1., 2., 3.], np.float32)
x = nd.array(_x)

out1 = nd.exp(x)
out2 = np.e ** x #np.e = 2.718281828459045
print(out1.asnumpy())
assert np.allclose(out1.asnumpy(), out2.asnumpy())

_out = np.exp(_x)
assert np.array_equal(out1.asnumpy(), _out) # nd.exp == np.exp

[  2.71828175   7.38905621  20.08553696]


Q18. Compute natural logarithm of x element-wise.

In [56]:
_x = np.array([1, np.e, np.e**2])
x = nd.array(_x)

out = nd.log(x)
print(out.asnumpy())

_out = np.log(_x)
assert np.array_equal(out.asnumpy(), _out) # nd.log == np.log

[ 0.  1.  2.]


Q19. Compute the max of x and y element-wise.

In [57]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 2])
x = nd.array(_x)
y = nd.array(_y)

out1 = nd.maximum(x, y)
out2 = nd.where(x > y, x, y)
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = np.maximum(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.maximum == np.maximum

[ 2.  5.  4.]


Q20. Compute the min of x and y element-wise.

In [58]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 2])
x = nd.array(_x)
y = nd.array(_y)

out1 = nd.minimum(x, y)
out2 = nd.where(x < y, x, y)
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

_out = np.minimum(_x, _y)
assert np.array_equal(out1.asnumpy(), _out) # nd.minimum == np.minimum

[ 1.  3.  2.]


Q21. Compute the sine, cosine, and tangent of x, element-wise.

In [61]:
_x = np.array([-np.pi, np.pi, np.pi/2])
x = nd.array(_x, dtype='float64')

out1 = nd.sin(x)
out2 = nd.cos(x)
out3 = nd.tan(x)
print(out1.asnumpy())
print(out2.asnumpy())
print(out3.asnumpy())

_out1 = np.sin(_x)
_out2 = np.cos(_x)
_out3 = np.tan(_x)

assert np.allclose(out1.asnumpy(), _out1) # nd.sin == np.sin
assert np.allclose(out2.asnumpy(), _out2) # nd.cos == np.cos
assert np.allclose(out3.asnumpy(), _out3) # nd.tan == np.tan

[ -1.22464680e-16   1.22464680e-16   1.00000000e+00]
[ -1.00000000e+00  -1.00000000e+00   6.12323400e-17]
[  1.22464680e-16  -1.22464680e-16   1.63312394e+16]


Q22. Compute (x - y)(x - y) element-wise.

In [70]:
_x = np.array([2, 3, 4])
_y = np.array([1, 5, 1])
x = nd.array(_x)
y = nd.array(_y)

out1 = nd.square(x - y)
out2 = nd.square(nd.subtract(x, y))
print(out1.asnumpy())
assert np.array_equal(out1.asnumpy(), out2.asnumpy())

[ 1.  4.  9.]
