# Tensor Transformations

[Solutions](Tensor_Transformations_Solutions.ipynb)

In [1]:
from __future__ import print_function
import mxnet
from mxnet import nd
import numpy as np

In [2]:
from datetime import date
date.today()

datetime.date(2017, 12, 28)

In [3]:
author = "lambdaofgod. based on https://github.com/Kyubyong/tensorflow-exercises"

In [4]:
mxnet.__version__

'1.0.0'

In [5]:
np.__version__

'1.12.1'

NOTE on notation
* _x, _y, _z, ...: NumPy 0-d or 1-d arrays
* _X, _Y, _Z, ...: NumPy 2-d or higer dimensional arrays
* x, y, z, ...: 0-d or 1-d tensors
* X, Y, Z, ...: 2-d or higher dimensional tensors

## Casting

Q1. Let X be a tensor of [["1.1", "2.2"], ["3.3", "4.4"]]. Convert the datatype of X to float32.

In [6]:
_X = np.array([["1.1", "2.2"], ["3.3", "4.4"]])
out = ???
print(out)
assert np.allclose(out.asnumpy(), _X.astype(np.float32))


[[ 1.10000002  2.20000005]
 [ 3.29999995  4.4000001 ]]
<NDArray 2x2 @cpu(0)>


Q2. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float64.

In [7]:
_X = np.array([[1, 2], [3, 4]], dtype=np.int32)
out1 = ???
out2 = ???
assert np.allclose(out1.asnumpy(), out2.asnumpy())
print(out1.asnumpy())
assert np.allclose(out1.asnumpy(), _X.astype(np.float64))

[[ 1.  2.]
 [ 3.  4.]]


Q3. Let X be a tensor [[1, 2], [3, 4]] of int32. Convert the data type of X to float32.

In [8]:
_X = np.array([[1, 2], [3, 4]], dtype=np.int32)
out1 = ???
out2 = ???
assert np.allclose(out1.asnumpy(), out2.asnumpy())
print(out1.asnumpy())
assert np.allclose(out1.asnumpy(), _X.astype(np.float32))

[[ 1.  2.]
 [ 3.  4.]]


Q4. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int32.

In [9]:
_X = np.array([[1, 2], [3, 4]], dtype=np.float32)
out1 = ???
assert np.allclose(out1.asnumpy(), _X)
print(out1.asnumpy())

[[1 2]
 [3 4]]


Q5. Let X be a tensor [[1, 2], [3, 4]] of float32. Convert the data type of X to int64.

In [10]:
_X = np.array([[1, 2], [3, 4]], dtype=np.float32)
out1 = ???
assert np.allclose(out1.asnumpy(), _X)
print(out1.asnumpy())

[[1 2]
 [3 4]]


## Slicing and Joining

Q6. Let X be a tensor<br/>
[[[1, 1, 1], [2, 2, 2]],<br/>
[[3, 3, 3], [4, 4, 4]],<br/>
[[5, 5, 5], [6, 6, 6]]].<br/>
Extract the [[[3, 3, 3], [5, 5, 5]] from X.

In [17]:
_X = np.array([[[1, 1, 1], 
                 [2, 2, 2]],
                [[3, 3, 3], 
                 [4, 4, 4]],
                [[5, 5, 5], 
                 [6, 6, 6]]])
X = nd.array(_X)
out = ??? 
print(out)


[[ 3.  3.  3.]
 [ 5.  5.  5.]]
<NDArray 2x3 @cpu(0)>


Q7. Let X be a tensor of<br/>
[[ 1  2]<br />
 [ 3  4]<br />
 [ 5  6]<br />
 [ 7  8]<br />
 [ 9 10]].<br />
 Extract the [[1, 2], [5, 6], [9, 10]]] from X.
 

In [5]:
_X = np.arange(1, 11).reshape([5, 2])
X = nd.array(_X)
out = ??? 
print(out)
assert np.allclose(out.asnumpy(), _X[[0, 2, 4]])


[[  1.   2.]
 [  5.   6.]
 [  9.  10.]]
<NDArray 3x2 @cpu(0)>


Q7. Let X be a tensor of<br/>
[[ 1  2  3  4  5]<br />
 [ 6  7  8  9  10]].<br />
Split X into 5 same-sized tensors along the second dimension.

In [25]:
_X = np.arange(1, 11).reshape([2, 5])
X = nd.array(_X)
out = ???
print(out)
comp = np.array_split(_X, 5, 1) 
assert np.allclose([each.asnumpy() for each in out], comp)

[
[[ 1.]
 [ 6.]]
<NDArray 2x1 @cpu(0)>, 
[[ 2.]
 [ 7.]]
<NDArray 2x1 @cpu(0)>, 
[[ 3.]
 [ 8.]]
<NDArray 2x1 @cpu(0)>, 
[[ 4.]
 [ 9.]]
<NDArray 2x1 @cpu(0)>, 
[[  5.]
 [ 10.]]
<NDArray 2x1 @cpu(0)>]


Q8. Lex X be a tensor<br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
Create a tensor looking like <br/>
[[ 1 2 3 1 2 3 1 2 3 ]<br/>
 [ 4 5 6 4 5 6 4 5 6 ]].

In [28]:
_X = np.arange(1, 7).reshape((2, 3))
X = nd.array(_X)
out = ??? 
print(out)
assert np.allclose(out.asnumpy(), np.tile(_X, [1, 3]))


[[ 1.  2.  3.  1.  2.  3.  1.  2.  3.]
 [ 4.  5.  6.  4.  5.  6.  4.  5.  6.]]
<NDArray 2x9 @cpu(0)>


Q9. Let X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
Pad 2 * 0's before the first dimension, 3 * 0's after the second dimension.

**Unsuported** as of 0.12. You'd get `Current implementation only supports 4-D or 5-D input.` for the appropriate method.

In [34]:
_X = np.arange(1, 7).reshape((2, 3))
X = nd.array(_X)
out = ???
print(out)
assert np.allclose(out.asnumpy(), np.pad(_X, [[2, 0], [0, 3]], 'constant', constant_values=[0, 0]))

MXNetError: [13:49:48] src/operator/./pad-inl.h:204: Current implementation only supports 4-D or 5-D input.

Stack trace returned 10 entries:
[bt] (0) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x29) [0x7f8b11431749]
[bt] (1) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(_ZNK5mxnet2op7PadProp10InferShapeEPSt6vectorIN4nnvm6TShapeESaIS4_EES7_S7_+0x189) [0x7f8b1369a079]
[bt] (2) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(+0x23fe202) [0x7f8b13509202]
[bt] (3) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(_ZN5mxnet10imperative12SetShapeTypeERKNS_7ContextERKN4nnvm9NodeAttrsERKSt6vectorIPNS_7NDArrayESaISA_EESE_PNS_12DispatchModeE+0x98d) [0x7f8b1357786d]
[bt] (4) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(_ZN5mxnet10Imperative6InvokeERKNS_7ContextERKN4nnvm9NodeAttrsERKSt6vectorIPNS_7NDArrayESaISA_EESE_+0x308) [0x7f8b1355df98]
[bt] (5) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(_Z22MXImperativeInvokeImplPviPS_PiPS0_iPPKcS5_+0x16e) [0x7f8b1399f46e]
[bt] (6) /opt/anaconda3/envs/nnets/lib/python3.5/site-packages/mxnet/libmxnet.so(MXImperativeInvokeEx+0x5b) [0x7f8b1399ff4b]
[bt] (7) /opt/anaconda3/envs/nnets/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call_unix64+0x4c) [0x7f8b38a46540]
[bt] (8) /opt/anaconda3/envs/nnets/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(ffi_call+0x1f5) [0x7f8b38a45ce5]
[bt] (9) /opt/anaconda3/envs/nnets/lib/python3.5/lib-dynload/_ctypes.cpython-35m-x86_64-linux-gnu.so(_ctypes_callproc+0x3dc) [0x7f8b38a3d7fc]


Q10. Let X be a tensor <br/>
[[ 1 2 3]<br/>
 [ 4 5 6].<br/>
and Y be a tensor<br/>
[[ 7 8 9]<br/>
 [10 11 12]].<br/>
Concatenate X and Y so that the new tensor looks like [[1, 2, 3, 7, 8, 9], [4, 5, 6, 10, 11, 12]].

In [43]:
_X = np.array([[1, 2, 3], [4, 5, 6]])
_Y = np.array([[7, 8, 9], [10, 11, 12]])
X = nd.array(_X)
Y = nd.array(_Y)
out = ??? 
print(out)
assert np.allclose(out.asnumpy(), np.concatenate((_X, _Y), 1))


[[  1.   2.   3.   7.   8.   9.]
 [  4.   5.   6.  10.  11.  12.]]
<NDArray 2x6 @cpu(0)>


Q11. Let x, y, and z be tensors [1, 4], [2, 5], and [3, 6], respectively. <br/>Create a single tensor from these such that it looks [[1, 2, 3], [4, 5, 6]].

In [44]:
x = nd.array([1, 4])
y = nd.array([2, 5])
z = nd.array([3, 6])
out = ??? 
print(out)


[[ 1.  2.  3.]
 [ 4.  5.  6.]]
<NDArray 2x3 @cpu(0)>


Q12. Let X be a tensor [[1, 2, 3], [4, 5, 6]]. Convert X into Y such that Y looks like [[1, 4], [2, 5], [3, 6]].

In [49]:
X = nd.array([[1, 2, 3], [4, 5, 6]])
Y = ??? 
print(Y)


[[ 1.  4.]
 [ 2.  5.]
 [ 3.  6.]]
<NDArray 3x2 @cpu(0)>


Q13. Given X below, reverse the sequence along the second axis except the zero-paddings. 

In [53]:
X = nd.array(
[[[0, 0, 1],
  [0, 1, 0],
  [0, 0, 0]],
 
 [[0, 0, 1],
  [0, 1, 0],
  [1, 0, 0]]])

out = ??? 
out


[[[ 0.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]

 [[ 1.  0.  0.]
  [ 0.  1.  0.]
  [ 0.  0.  1.]]]
<NDArray 2x3x3 @cpu(0)>

Q14. Given X below, reverse the last dimension.

In [59]:
_X = np.arange(1, 1*2*3*4 + 1).reshape((1, 2, 3, 4))
X = nd.array(_X)
out = ??? 
print(out.asnumpy())
assert np.allclose(out.asnumpy(), _X[:, :, :, ::-1])

[[[[  4.   3.   2.   1.]
   [  8.   7.   6.   5.]
   [ 12.  11.  10.   9.]]

  [[ 16.  15.  14.  13.]
   [ 20.  19.  18.  17.]
   [ 24.  23.  22.  21.]]]]


Q15. Given X below, permute its dimensions such that the new tensor has shape (3, 1, 2).

In [63]:
_X = np.ones((1, 2, 3))
X = nd.array(_X)
out = ??? 
print(out.shape)
assert np.allclose(out.asnumpy(), np.transpose(_X))

(3, 1, 2)


Q16. Let X be a tensor [[7, 8], [5, 6]] and Y be a tensor [[1, 2], [3, 4]]. Create a single tensor looking like [[1, 2], [3, 4], [5, 6], [7, 8]].

In [79]:
X = nd.array([[7, 8], [5, 6]])
Y = nd.array([[1, 2], [3, 4]])
out = ??? 
print(out)


[[ 1.  2.]
 [ 3.  4.]
 [ 5.  6.]
 [ 7.  8.]]
<NDArray 4x2 @cpu(0)>


Q17. Let x be a tensor [0, 1, 2, 3] and y be a tensor [True, False, False, True].<br/>
Apply mask y to x.

**Unsupported** as of mxnet 0.12. see [this github issue](https://github.com/apache/incubator-mxnet/issues/7443)

Q18. Let X be a tensor [[0, 5, 3], [4, 2, 1]]. Convert X into one-hot.

In [91]:
X = nd.array([[0, 5, 3], [4, 2, 1]])
out = ??? 
print(out)


[[[ 1.  0.  0.  0.  0.  0.]
  [ 0.  0.  0.  0.  0.  1.]
  [ 0.  0.  0.  1.  0.  0.]]

 [[ 0.  0.  0.  0.  1.  0.]
  [ 0.  0.  1.  0.  0.  0.]
  [ 0.  1.  0.  0.  0.  0.]]]
<NDArray 2x3x6 @cpu(0)>
